export const products = [
  {
    date: '23/09/24',
    image:
      'https://m.media-amazon.com/images/I/71GTKbwnMQL._AC_UL640_FMwebp_QL65_.jpg',
    mrp: '870',
    name: 'Udhaya Krishna GHEE 1 Litre',
    cost: '860',
    quantity: '2',
    supplierName: 'Ram',
  },
  {
    date: '22/09/2024',
    image: 'https://m.media-amazon.com/images/I/61veURra7rL._AC_UL640_FMwebp_QL65_.jpg',
    mrp: '410',
    name: 'Tata Tea Chakra Gold Dust Tea | 500 Grams',
    cost: '357',
    quantity: '2.3',
    supplierName: 'Ram',
  },
  {
    date: '22/09/2024',
    image: 'https://m.media-amazon.com/images/I/71eWD5xjijL._AC_UL640_FMwebp_QL65_.jpg',
    mrp: '269',
    name: 'Tata Sampann Unpolished Toor Dal/Arhar Dal, 1kg',
    cost: '236',
    quantity: '2',
    supplierName: 'Ram',
  },
  {
    date: '18/09/2024',
    image: 'https://m.media-amazon.com/images/I/71BsckBgy3L._AC_UL640_FMwebp_QL65_.jpg',
    mrp: '499',
    name: "Kellogg's Muesli Fruit Nut & Seeds 750G",
    cost: '313',
    quantity: '94',
    supplierName: 'Ram',
  },
  {
    date: '17/08/2024',
    image: 'https://m.media-amazon.com/images/I/617wuLJioFL._AC_UL640_FMwebp_QL65_.jpg',
    mrp: '250',
    name: 'Nuts About You RAISIN, 500 g',
    cost: '159',
    quantity: '3',
    supplierName: 'Ram',
  },
  {
    date: '19/02/2024',
    image: 'https://m.media-amazon.com/images/I/61-zRoFrfqL._AC_UL640_FMwebp_QL65_.jpg',
    mrp: '28',
    name: 'Tata Salt, 1kg',
    cost: '24',
    quantity: '2.3',
    supplierName: 'Ram',
  },
  {
    date: '12/08/2024',
    image: 'https://m.media-amazon.com/images/I/81-J0Qwn50L._AC_UL640_FMwebp_QL65_.jpg',
    mrp: '399',
    name: 'Dabur Honey Squeezy Pack 800g',
    cost: '279',
    quantity: '2',
    supplierName: 'Ram',
  },
  // {
  //   date: '',
  //   image: '',
  //   mrp: '₹',
  //   name: '',
  //   cost: '₹',
  //   quantity: '',
  //   supplierName: 'Ram',
  // },
];
